# This workflow will build a Java project 

name: Build Run and Test - Receiver code

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build and Generate coverage - Receiver code
      run: mvn test jacoco:report
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage - Receiver code
        path: ./target/site/jacoco
        retention-days: 21
